In [ ]:
import pandas as pd
import numpy as np
import xlrd
from datetime import datetime,timedelta

In [ ]:
X_np_shape=(2606, 60, 4)

In [ ]:
# retrieving data from file. 
loaded_X = np.loadtxt("X.txt") 
x_np=(2606, 60, 4)
# This loadedArr is a 2D array, therefore 
# we need to convert it to the original 
# array shape.reshaping to get original 
# matrice with original shape. 
load_original_X = loaded_X.reshape(loaded_X.shape[0], loaded_X.shape[1] // X_np_shape[2], X_np_shape[2]) 

In [ ]:
np.shape(load_original_X)

(2606, 60, 4)

In [ ]:
load_original_X[:2]

array([[[ 7.4498e+02,  4.4700e+00,  9.3908e+02,  1.3500e+00],
        [ 7.4655e+02, -2.0400e+00,  9.3338e+02, -1.1300e+00],
        [ 7.4295e+02,  5.7000e-01,  9.4403e+02,  2.8000e-01],
        [ 7.4610e+02,  5.0500e+00,  9.3720e+02,  1.4300e+00],
        [ 7.4723e+02,  8.0500e+00,  9.3255e+02,  1.5700e+00],
        [ 7.4580e+02,  2.8000e-01,  9.3660e+02, -6.0000e-01],
        [ 7.4415e+02,  7.2800e+00,  9.3758e+02,  1.5600e+00],
        [ 7.4715e+02,  2.8300e+00,  9.3008e+02,  3.0000e-01],
        [ 7.4798e+02,  3.9700e+00,  9.3713e+02,  2.4000e-01],
        [ 7.4708e+02,  3.6900e+00,  9.3675e+02,  1.5200e+00],
        [ 7.4895e+02,  4.0900e+00,  9.3330e+02,  6.5000e-01],
        [ 7.4693e+02,  4.0700e+00,  9.3495e+02,  1.1600e+00],
        [ 7.4430e+02,  5.7000e+00,  9.3750e+02,  1.3300e+00],
        [ 7.4513e+02,  3.4600e+00,  9.3503e+02,  2.6000e-01],
        [ 7.4145e+02,  4.9700e+00,  9.3938e+02,  1.0800e+00],
        [ 7.4573e+02,  2.8400e+00,  9.3030e+02,  7.7000e-01],
        

In [ ]:
load_original_y = np.loadtxt("y.txt") 
load_original_y=load_original_y.reshape(load_original_y.shape[0],1)
np.shape(load_original_y)

(2606, 1)

In [ ]:
for i in range(3):
  print(load_original_X[i], load_original_y[i])

[[ 7.4498e+02  4.4700e+00  9.3908e+02  1.3500e+00]
 [ 7.4655e+02 -2.0400e+00  9.3338e+02 -1.1300e+00]
 [ 7.4295e+02  5.7000e-01  9.4403e+02  2.8000e-01]
 [ 7.4610e+02  5.0500e+00  9.3720e+02  1.4300e+00]
 [ 7.4723e+02  8.0500e+00  9.3255e+02  1.5700e+00]
 [ 7.4580e+02  2.8000e-01  9.3660e+02 -6.0000e-01]
 [ 7.4415e+02  7.2800e+00  9.3758e+02  1.5600e+00]
 [ 7.4715e+02  2.8300e+00  9.3008e+02  3.0000e-01]
 [ 7.4798e+02  3.9700e+00  9.3713e+02  2.4000e-01]
 [ 7.4708e+02  3.6900e+00  9.3675e+02  1.5200e+00]
 [ 7.4895e+02  4.0900e+00  9.3330e+02  6.5000e-01]
 [ 7.4693e+02  4.0700e+00  9.3495e+02  1.1600e+00]
 [ 7.4430e+02  5.7000e+00  9.3750e+02  1.3300e+00]
 [ 7.4513e+02  3.4600e+00  9.3503e+02  2.6000e-01]
 [ 7.4145e+02  4.9700e+00  9.3938e+02  1.0800e+00]
 [ 7.4573e+02  2.8400e+00  9.3030e+02  7.7000e-01]
 [ 7.4348e+02  3.3200e+00  9.3893e+02  8.1000e-01]
 [ 7.4423e+02  5.1600e+00  9.3368e+02  6.3000e-01]
 [ 7.4633e+02  3.0100e+00  9.3045e+02  8.1000e-01]
 [ 7.4205e+02  3.9400e+00  9.39

In [ ]:
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
scaler.fit(load_original_y)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
load_original_y_t=scaler.transform(load_original_y)

In [ ]:
n_steps= np.shape(load_original_X)[1]
n_features= np.shape(load_original_X)[2]
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=4, activation='relu', input_shape=(n_steps, n_features)))
model.add(Conv1D(filters=128,kernel_size=4, activation='relu'))
model.add(MaxPooling1D(pool_size=4))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
np.shape(load_original_X[:2200])

(2200, 60, 4)

In [ ]:
model.fit(array(load_original_X[:2200]).astype('float32'), array(load_original_y_t[:2200]).astype('float32'), epochs=1800, verbose=1)

Epoch 1/1800
69/69 [==============================] - 0s 3ms/step - loss: 770.4360
Epoch 2/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0575
Epoch 3/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0397
Epoch 4/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0398
Epoch 5/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0419
Epoch 6/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0442
Epoch 7/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0404
Epoch 8/1800
69/69 [==============================] - 0s 3ms/step - loss: 0.0383
Epoch 9/1800
69/69 [==============================] - 0s 3ms/step - loss: 0.0481
Epoch 10/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0511
Epoch 11/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0454
Epoch 12/1800
69/69 [==============================] - 0s 2ms/step - loss: 0.0477
Epoch 13/1800
69/69 [==

In [ ]:
x_input = load_original_X[2].reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)

In [ ]:
yhat = model.predict(load_original_X[2200:],verbose=0)

In [ ]:
scaler.inverse_transform(yhat)

array([[82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.70616],
       [82.7

In [ ]:
load_original_y[2200:]

array([[79.4],
       [81. ],
       [78.5],
       [77.5],
       [77. ],
       [77.5],
       [76. ],
       [76.4],
       [76.7],
       [79. ],
       [81. ],
       [82.2],
       [83.8],
       [85. ],
       [84.5],
       [83.5],
       [80.5],
       [81.6],
       [82.2],
       [83.1],
       [83.9],
       [83.7],
       [82.3],
       [82.5],
       [83.7],
       [82.5],
       [83.6],
       [84.8],
       [85.9],
       [86.5],
       [87. ],
       [87.5],
       [87. ],
       [87.5],
       [87.1],
       [86.5],
       [86.6],
       [86.3],
       [86. ],
       [86.2],
       [86.4],
       [86. ],
       [86.4],
       [86.9],
       [86.5],
       [86.8],
       [85.5],
       [86.1],
       [84. ],
       [85. ],
       [85.5],
       [86. ],
       [86.5],
       [87.2],
       [86.8],
       [85.5],
       [86. ],
       [86.3],
       [86. ],
       [86.8],
       [86.4],
       [86.2],
       [85.8],
       [84.2],
       [84.6],
       [85.1],
       [85